// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Greet(arg1:string):Promise<string>;

export function PinExists(arg1:string):Promise<dto.QueryPinReponse>;
